name: CI

on: [push, pull_request]

env:
  SDRPLAY_SOFTWARE_DOWNLOADS: 'https://www.sdrplay.com/software'

jobs:
  macos-test:
    name: MacOS test
    runs-on: macos-latest
    steps:
      - name: Check MacOS version
        run: sw_vers
      - name: Install SDRplay API 3.X
        env:
          SDRPLAY_API_FILE_MACOS: SDRplayAPI-macos-installer-universal-3.15.0.pkg
        run: |
          curl -s -S -O "$SDRPLAY_SOFTWARE_DOWNLOADS/$SDRPLAY_API_FILE_MACOS"
          sudo installer -pkg "$SDRPLAY_API_FILE_MACOS" -target /
      - name: Check SDRplay API install
        run: |
          ls -l /usr/local/lib
          otool -T -R -M /usr/local/lib/libsdrplay_api.so
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        run: cc -o sdrplay_api_version sdrplay_api_version.c -lsdrplay_api
        #run: cc -o sdrplay_api_version sdrplay_api_version.c /Library/SDRplayAPI/3.15.0/lib/libsdrplay_api.so.3.15
      - name: Check things
        run: |
          otool -l -v sdrplay_api_version
      - name: Run
        run: ./sdrplay_api_version
