name: CI

on: [push, pull_request]

env:
  SDRPLAY_SOFTWARE_DOWNLOADS: 'https://www.sdrplay.com/software'

jobs:
  macos-test:
    name: MacOS test
    runs-on: macos-latest
    steps:
      - name: Check MacOS version
        run: sw_vers
      - name: Install SDRplay API 3.X
        env:
          SDRPLAY_API_FILE_MACOS: SDRplayAPI-macos-installer-universal-3.15.1.pkg
        run: |
          curl -s -S -O "$SDRPLAY_SOFTWARE_DOWNLOADS/$SDRPLAY_API_FILE_MACOS"
          sudo installer -pkg "$SDRPLAY_API_FILE_MACOS" -target /
      - name: Check SDRplay API install
        run: |
          ls -l /usr/local/lib
          echo '--------------------------------------'
          otool -L /usr/local/lib/libsdrplay_api.so
          echo '--------------------------------------'
          otool -L /Library/SDRplayAPI/3.15.1/lib/libsdrplay_api.so.3.15
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        #run: cc -v -o sdrplay_api_version sdrplay_api_version.c -lsdrplay_api -rpath /usr/local/lib
        run: |
          cc -v -o sdrplay_api_version sdrplay_api_version.c -rpath /usr/local/lib -lsdrplay_api
          install_name_tool -change libsdrplay_api.so.3 @rpath/libsdrplay_api.so.3 sdrplay_api_version
        #run: cc -o sdrplay_api_version sdrplay_api_version.c /Library/SDRplayAPI/3.15.1/lib/libsdrplay_api.so.3.15
      - name: Check things
        run: |
          otool -L sdrplay_api_version
          echo '--------------------------------------'
          otool -l sdrplay_api_version
      - name: Run
        run: ./sdrplay_api_version
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            sdrplay_api_version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
